"use strict";
const CHECKS={
"Contacts & Access":["Venue and loading address","Promoter contact and mobile","Venue / duty manager contact","Production contact","Emergency / security contact","Parking and permits","Loading route, stairs or lift"],
"Deal & Settlement":["Fee, guarantee or split","Deal memo checked","Settlement contact and time","Payment and invoice details","Expected deductions","Merch commission"],
"Schedule":["Access / load-in","Crew call","Soundcheck / line check","Doors","Support stage time","Headline stage time","Curfew","Load-out deadline"],
"Technical":["Technical rider received","Stage dimensions","PA / FOH","Monitors","Lighting","Stage plot and input list","Backline","Power and local crew"],
"Hospitality & Backstage":["Dressing room","Hospitality rider","Meal or buyout","Dietary needs","Water and towels","Quiet / private space"],
"Wellbeing & Access":["Access requirements","Step-free route","Accessible toilet","Rest time protected","Pressure points reviewed","Unwell escalation contact","Reasonable adjustments"],
"Security & Guests":["Guest list process","Passes / laminates","Photo passes","Meet and greet","Security briefing","Safe storage"],
"Merchandise":["Selling position","Table, light and power","Seller agreed","Card signal / Wi-Fi","Opening stock","Commission settlement","Closing reconciliation"],
"Travel & Hotel":["Route and journey time","Driver breaks","Hotel and reference","Late check-in","Overnight parking","Next departure"]};
const COST_CATS=["Tour manager","Driver","Other crew","Artist / musician fees","Van / vehicle","Trailer","Fuel","Parking / tolls","Ferry / rail / flights","Accommodation","Subsistence / per diems","Rehearsal","Production / equipment","Backline","Insurance","Marketing / PR","Merch production","Access costs","Visas / permits","Admin","Other"];
const DEFAULT={meta:{artist:"",tour:"",start:"",end:"",prepared:"",contingency:5},income:{funding:0,artist:0,other:0},costs:[],shows:[],merch:[],cash:[],advances:[]};
let state=load()||structuredClone(DEFAULT),activeAdvance=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(Number(n)||0),id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"_"+Math.random();
function load(){try{return JSON.parse(localStorage.getItem("tm360ToolsV1"))}catch{return null}}
function save(){localStorage.setItem("tm360ToolsV1",JSON.stringify(state));updateAll()}
function num(v){return Number(v)||0}
function calculations(){const show=state.shows.reduce((a,s)=>a+showIncome(s),0),merch=state.merch.reduce((a,m)=>a+merchMargin(m),0),other=num(state.income.funding)+num(state.income.artist)+num(state.income.other),base=state.costs.reduce((a,c)=>a+num(c.qty)*num(c.unit),0),cont=base*num(state.meta.contingency)/100,cost=base+cont,income=show+merch+other;return{show,merch,income,cost,position:income-cost}}
function showIncome(s){const gross=num(s.ticket)*num(s.paid);if(s.deal==="Door Split")return gross;if(s.deal==="Guarantee + Split")return num(s.guarantee)+gross;return num(s.guarantee)}
function merchMargin(m){return (num(m.price)*num(m.units)*(1-num(m.commission)/100))-(num(m.cost)*num(m.units))}
function completion(a){const vals=Object.values(a.items||{}),total=Object.values(CHECKS).flat().length,done=vals.filter(x=>x.done).length;return total?Math.round(done/total*100):0}
function bindMeta(){[["artistName","artist"],["tourName","tour"],["startDate","start"],["endDate","end"],["preparedBy","prepared"],["contingency","contingency"]].forEach(([el,k])=>{const e=$("#"+el);e.value=state.meta[k]??"";e.oninput=()=>{state.meta[k]=e.value;save()}});[["fundingRequested","funding"],["artistContribution","artist"],["otherIncome","other"]].forEach(([el,k])=>{const e=$("#"+el);e.value=state.income[k]||"";e.oninput=()=>{state.income[k]=e.value;save()}})}
function option(values,current){return values.map(v=>`<option ${v===current?"selected":""}>${v}</option>`).join("")}
function renderCosts(){const b=$("#costRows");b.innerHTML="";state.costs.forEach((c,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td><select data-k="cat">${option(COST_CATS,c.cat)}</select></td><td><input data-k="desc" value="${esc(c.desc)}"></td><td><select data-k="status">${option(["Estimated","Quoted","Confirmed","Paid"],c.status)}</select></td><td><input data-k="qty" type="number" min="0" step=".1" value="${c.qty}"></td><td><input data-k="unit" type="number" min="0" step=".01" value="${c.unit}"></td><td class="row-total">${money(num(c.qty)*num(c.unit))}</td><td><button class="remove">×</button></td>`;tr.querySelectorAll("[data-k]").forEach(e=>e.oninput=()=>{c[e.dataset.k]=e.value;save()});tr.querySelector(".remove").onclick=()=>{state.costs.splice(i,1);save()};b.append(tr)})}
function renderShows(){const b=$("#showRows");b.innerHTML="";state.shows.forEach((s,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td><input data-k="date" type="date" value="${s.date||""}"></td><td><input data-k="venue" value="${esc(s.venue)}" placeholder="Venue, city"></td><td><select data-k="deal">${option(["Guarantee","Door Split","Guarantee + Split","Festival Fee","Other"],s.deal)}</select></td><td><input data-k="guarantee" type="number" value="${s.guarantee}"></td><td><input data-k="ticket" type="number" value="${s.ticket}"></td><td><input data-k="paid" type="number" value="${s.paid}"></td><td class="row-total">${money(showIncome(s))}</td><td><select data-k="status">${option(["Confirmed","Provisional","Estimated","Cancelled"],s.status)}</select></td><td><button class="remove">×</button></td>`;tr.querySelectorAll("[data-k]").forEach(e=>e.oninput=()=>{s[e.dataset.k]=e.value;save()});tr.querySelector(".remove").onclick=()=>{state.shows.splice(i,1);save()};b.append(tr)})}
function renderMerch(){const b=$("#merchRows");b.innerHTML="";state.merch.forEach((m,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td><input data-k="item" value="${esc(m.item)}"></td><td><input data-k="cost" type="number" value="${m.cost}"></td><td><input data-k="price" type="number" value="${m.price}"></td><td><input data-k="units" type="number" value="${m.units}"></td><td><input data-k="commission" type="number" value="${m.commission}"></td><td class="row-total">${money(merchMargin(m))}</td><td><button class="remove">×</button></td>`;tr.querySelectorAll("[data-k]").forEach(e=>e.oninput=()=>{m[e.dataset.k]=e.value;save()});tr.querySelector(".remove").onclick=()=>{state.merch.splice(i,1);save()};b.append(tr)})}
function renderCash(){const b=$("#cashRows");b.innerHTML="";let balance=0;state.cash.sort((a,b)=>(a.date||"").localeCompare(b.date||""));state.cash.forEach((c,i)=>{balance+=num(c.in)-num(c.out);const tr=document.createElement("tr");tr.innerHTML=`<td><input data-k="date" type="date" value="${c.date||""}"></td><td><select data-k="type">${option(["Income","Expenditure"],c.type)}</select></td><td><input data-k="desc" value="${esc(c.desc)}"></td><td><input data-k="in" type="number" value="${c.in}"></td><td><input data-k="out" type="number" value="${c.out}"></td><td class="row-total">${money(balance)}</td><td><select data-k="status">${option(["Expected","Invoiced","Paid","Received","Overdue"],c.status)}</select></td><td><button class="remove">×</button></td>`;tr.querySelectorAll("[data-k]").forEach(e=>e.oninput=()=>{c[e.dataset.k]=e.value;save()});tr.querySelector(".remove").onclick=()=>{state.cash.splice(i,1);save()};b.append(tr)})}
function newAdvance(){const items={};Object.values(CHECKS).flat().forEach(x=>items[x]={done:false,status:"Outstanding",note:""});return{id:id(),date:"",venue:"New show",city:"",contact:"",items}}
function renderAdvance(){const l=$("#advanceShowList");l.innerHTML="";state.advances.forEach(a=>{const c=document.createElement("div");c.className="show-card "+(a.id===activeAdvance?"active":"");c.innerHTML=`<strong>${esc(a.venue||"Untitled show")}</strong><small>${esc(a.city||"")} ${a.date||""}</small><div class="progress"><i style="width:${completion(a)}%"></i></div>`;c.onclick=()=>{activeAdvance=a.id;renderAdvance()};l.append(c)});const a=state.advances.find(x=>x.id===activeAdvance);const d=$("#advanceDetail");if(!a){d.innerHTML='<div class="empty">Add or select a show to start the advance.</div>';return}d.innerHTML=`<div class="section-head"><div><p class="eyebrow">${completion(a)}% complete</p><h2>${esc(a.venue)}</h2></div><button class="remove" id="deleteAdvance">Delete show</button></div><div class="advance-meta"><label>Venue<input data-meta="venue" value="${esc(a.venue)}"></label><label>Town / city<input data-meta="city" value="${esc(a.city)}"></label><label>Date<input data-meta="date" type="date" value="${a.date||""}"></label><label>Main contact<input data-meta="contact" value="${esc(a.contact)}"></label></div><div id="advanceGroups"></div>`;d.querySelectorAll("[data-meta]").forEach(e=>e.oninput=()=>{a[e.dataset.meta]=e.value;save()});$("#deleteAdvance").onclick=()=>{state.advances=state.advances.filter(x=>x.id!==a.id);activeAdvance=state.advances[0]?.id||null;save()};const g=$("#advanceGroups");Object.entries(CHECKS).forEach(([name,items])=>{const sec=document.createElement("div");sec.className="advance-group";sec.innerHTML=`<h3>${name}</h3>`;items.forEach(label=>{a.items[label]??={done:false,status:"Outstanding",note:""};const v=a.items[label],row=document.createElement("div");row.className="check-row";row.innerHTML=`<input type="checkbox" ${v.done?"checked":""}><span>${label}</span><select>${option(["Outstanding","Provisional","Confirmed","N/A"],v.status)}</select><input type="text" placeholder="Notes / owner" value="${esc(v.note)}">`;const [check,,sel,note]=row.children;check.onchange=()=>{v.done=check.checked;if(check.checked&&v.status==="Outstanding")v.status="Confirmed";save()};sel.onchange=()=>{v.status=sel.value;v.done=["Confirmed","N/A"].includes(sel.value);save()};note.oninput=()=>{v.note=note.value;save()};sec.append(row)});g.append(sec)})}
function flags(){const c=calculations(),f=[];if(!state.meta.artist)f.push("Add the artist or band name.");if(!state.shows.length)f.push("Add at least one show.");if(!state.costs.length)f.push("Add the expected tour costs.");if(c.position<0)f.push(`Current funding shortfall: ${money(-c.position)}.`);if(state.advances.length&&state.advances.some(a=>completion(a)<100))f.push("One or more show advances are incomplete.");const el=$("#flags");el.innerHTML=f.length?f.map(x=>`<div class="flag">${x}</div>`).join(""):'<div class="flag ok">No immediate readiness flags.</div>'}
function updateAll(){const c=calculations(),adv=state.advances.length?Math.round(state.advances.reduce((a,x)=>a+completion(x),0)/state.advances.length):0,outstanding=state.advances.reduce((n,a)=>n+Object.values(a.items||{}).filter(x=>!x.done).length,0);$("#heroTour").textContent=state.meta.tour||"Untitled tour";$("#heroShows").textContent=state.shows.length;$("#heroPosition").textContent=money(c.position);[["kpiIncome",c.income],["kpiCosts",c.cost],["kpiPosition",c.position],["reviewPosition",c.position],["reviewCostPerShow",state.shows.length?c.cost/state.shows.length:0],["reviewIncomePerShow",state.shows.length?c.income/state.shows.length:0]].forEach(([x,v])=>{const e=$("#"+x);e.textContent=money(v);e.classList.toggle("negative",v<0);e.classList.toggle("positive",v>0)});$("#kpiAdvance").textContent=adv+"%";$("#reviewOutstanding").textContent=outstanding;renderCosts();renderShows();renderMerch();renderCash();renderAdvance();flags()}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function addHandlers(){ $$(".tab").forEach(t=>t.onclick=()=>{$$(".tab,.view").forEach(x=>x.classList.remove("active"));t.classList.add("active");$("#"+t.dataset.view).classList.add("active")});$("#addCost").onclick=()=>{state.costs.push({cat:"Tour manager",desc:"",status:"Estimated",qty:1,unit:0});save()};$("#addShow").onclick=()=>{state.shows.push({date:"",venue:"",deal:"Guarantee",guarantee:0,ticket:0,paid:0,status:"Estimated"});save()};$("#addMerch").onclick=()=>{state.merch.push({item:"T-shirt",cost:0,price:0,units:0,commission:0});save()};$("#addCash").onclick=()=>{state.cash.push({date:"",type:"Expenditure",desc:"",in:0,out:0,status:"Expected"});save()};$("#addAdvanceShow").onclick=()=>{const a=newAdvance();state.advances.push(a);activeAdvance=a.id;save()};$("#saveProject").onclick=()=>{save();alert("Draft saved on this device.")};$("#exportProject").onclick=()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`OFFICIAL_TM360_${(state.meta.tour||"Tour_Project").replace(/[^a-z0-9]/gi,"_")}.json`;a.click();URL.revokeObjectURL(a.href)};$("#importProject").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{state=JSON.parse(r.result);activeAdvance=state.advances?.[0]?.id||null;save();bindMeta()}catch{alert("That project file could not be read.")}};r.readAsText(f)};$("#printProject").onclick=()=>print();$("#newProject").onclick=()=>{if(confirm("Start a new project? Export the current project first if you need a backup.")){state=structuredClone(DEFAULT);activeAdvance=null;save();bindMeta()}}}
document.addEventListener("DOMContentLoaded",()=>{bindMeta();addHandlers();activeAdvance=state.advances?.[0]?.id||null;updateAll()});